### ISSUE TITLE
Head bug/suggestion 

### ISSUE THREAD

**Issue by Jacielegit** [heroslender/HeroSpawners#8]
/ en-us
Hello developer, I'm here to ask for something and request a fix / optimization on the mob heads.
The iron golem, snowman, giant, silverfish, bat, ocelot and horse heads are not working (ocelot is misspelled). The heads of Zumbi (dark background), Enderdragon / Endermite (unrecognizable), Witch (horrible) and these I only suggest to improve.
The optimization I was referring to is being able to shift and right click with a stack (2-64) and automatically put everyone in the stack.
/ pt-br
Olá desevolvedor, eu estou aqui para pedir uma coisa e solicitar uma correção/otimização nas cabeças de mob.
As cabeças de iron golem, snowman, giant, silverfish, bat, ocelot e horse não estão funcionando(MHF_ocelot está escrito errado, está "MHF_ozelot" por padrão). As cabeças de Zumbi(parte de baixo escura), Enderdragon/Endermite(irreconhecíveis), Witch (horrível) dou apenas a sugestão de melhorar.
A otimização que me referi é de poder usar shift e clicar com botão direito do mouse com um stack(2-64) e serem colocados automaticamente todos no stack.

Obs: Desconsiderei spawner de armor stand e de player ;-;
PrintScreen: https://prnt.sc/s1k6o3

**Comment by heroslender** [comment]
Cabeças de mobs são cabeças de players, e automatizei a geração da config para colocar todos tipos de mob com base nos fornecidos pela API do bukkit, ficando assim a lista completa independentemente da versão do servidor, usando a skin `MHF_{mob}` [fornecida pela mojang](https://minecraft.gamepedia.com/Head#Mojang_skins), por isso, é possivel sim que algumas cabeças não tenham uma skin funcional, mas também é possivel colocar outra skin lá na config. mas vou ver essas que mencionaste, arranjar outra skin que se adapte.

E a opção de colocar com shift já tem se for usado em conjunto com o [SilkSpawners](https://dev.bukkit.org/projects/silkspawners), se usares outro sem ser o SilkSpawners, manda o link dele que eu vejo o que posso fazer.

**Comment by Jacielegit** [comment]
https://www.spigotmc.org/resources/mineablespawners-1-8-1-15-silkspawners-alternative.59921/
^ (Mineablespawners) ^
Outra pergunta, tem como tirar todos os spawners de uma vez com o silkspawners?
Edit: estou a usar este pl de spawner pois ele tem como colocar o lvl de enchant de silk touch para remover o spawner, tipo: Toque suave 2 para remover spawner e o tipo de ferramenta, se for integrar com esse plugin, pfv coloca pra corresponder com a opção de não dropar xp da config.yml do mineablespawners. Obrigado pela atenção.

**Comment by heroslender** [comment]
> Outra pergunta, tem como tirar todos os spawners de uma vez com o silkspawners?

Todos não, vai só aos packs de 64.

**Comment by Jacielegit** [comment]
Tenho uma outra sugestão também: colocar uma modificação no plugin ou criar outro para não precisar de silkspawners ou afins, dai também pode colocar para remover spawners e receber a quantidade, em casos como o meu, estou a trabalhar num servidor OP e tenho objetivo de deixar player comprar mais de 50000 spawners, remover os spawners e ganhar um unico com item/block que quebra/coloca os 50000 instantaneamente. É algo que ajudaria.

**Comment by heroslender** [comment]
Feature adicionada.
