### ISSUE TITLE
Error with SilkSpawners + herospawners

### ISSUE THREAD

**Issue by Jacielegit** [heroslender/HeroSpawners#9]
Coloquei o plugin silkspawners pra usar junto com o herospawners e o herospawners ta dando uns erros estranhos e se torna não-utilizável, o ocorrido para quando remove o silkspawners.

**Comment by heroslender** [comment]
Provavelmente tu colocou o SilkSpawners errado, o correto seria esse: https://dev.bukkit.org/projects/silkspawners

**Comment by Jacielegit** [comment]
Oi, o erro ocorreu com o mineablespawners e o silkspawners v5.0.2, dai botei o v5.0.1 e deu certo. Tem alguma forma de corrigir a 5.0.2 ou ai n da problema?

**Comment by heroslender** [comment]
Tu está querendo usar o mineablespawners junto com o silkspawners, mas não sei se isso vai funcionar, porque os 2 tem a mesma funcionalidade.
Também já estive a ver a API do MineableSpawners e ela não tem eventos igual o SilkSpawners, para saber quando o player coloca/quebra spawners.

**Comment by Jacielegit** [comment]
Não utilizei os dois ao mesmo tempo, eu testei com os 2, e ambos fazem seu pl dar o mesmo erro ou parecido.

**Comment by heroslender** [comment]
hmm, manda o erro para eu ver qual é o problema.
Btw, já começei a desenvolver um sistema para pegar spawners, tipo SilkSpawners, na branch [release/4.0.0](https://github.com/heroslender/HeroSpawners/tree/release/4.0.0), mas ainda não tem data prevista para lançamento.

**Comment by heroslender** [comment]
Fechado por inatividade.
